### ISSUE TITLE
Allow logging to stderr

### ISSUE THREAD

**Issue by rgcjonas** [rvagg/github-webhook#8]
Logging with `--log=/dev/stderr` (or `/proc/self/fd/2`) fails if stderr is some kind of socket which cannot be opened as a file.

Usage scenario: I run it as a systemd service and want to log to the journal. Systemd will connect a socket to stderr which fails with `ENXIO` if you try to open it via `/dev/stderr`.

For now, I have it running with [this patch](https://github.com/rvagg/github-webhook/files/518396/github-webhook-stdout-hack.patch.txt) but it doesn't feel like a proper solution.

**Comment by rvagg** [comment]
yeah, good call, check this out for an option and leave a comment there: https://github.com/rvagg/github-webhook/pull/9
